# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160925_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='link',
            field=models.CharField(max_length=800),
        ),
    ]
