# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160925_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
