# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160925_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='full_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='full_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='full_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
