# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160925_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('final_test', models.FileField(upload_to='tests/final')),
                ('slide', models.FileField(upload_to='slides')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ModulesEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('final_test', models.FileField(upload_to='tests/final')),
                ('slide', models.FileField(upload_to='slides')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Module')),
            ],
        ),
    ]
