# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_courseenrollment_modulesenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='date_release',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
