# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160925_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesenrollment',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='final_test',
            field=models.FileField(blank=True, null=True, upload_to='tests/final'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='slide',
            field=models.FileField(blank=True, null=True, upload_to='slides'),
        ),
        migrations.AlterField(
            model_name='modulesenrollment',
            name='final_test',
            field=models.FileField(blank=True, null=True, upload_to='tests/final'),
        ),
        migrations.AlterField(
            model_name='modulesenrollment',
            name='slide',
            field=models.FileField(blank=True, null=True, upload_to='slides'),
        ),
    ]
