# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160925_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulesenrollment',
            name='order',
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
