# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160925_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
