# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_class_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulesenrollment',
            old_name='final_test',
            new_name='final_test_answer',
        ),
        migrations.RemoveField(
            model_name='module',
            name='date_release',
        ),
        migrations.RemoveField(
            model_name='module',
            name='status',
        ),
        migrations.RemoveField(
            model_name='modulesenrollment',
            name='slide',
        ),
        migrations.AddField(
            model_name='module',
            name='exercise',
            field=models.FileField(blank=True, null=True, upload_to='exercises'),
        ),
        migrations.AddField(
            model_name='module',
            name='slide',
            field=models.FileField(blank=True, null=True, upload_to='slides'),
        ),
        migrations.AddField(
            model_name='modulesenrollment',
            name='date_release',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='modulesenrollment',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
