# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_modulesenrollment_forum_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulesenrollment',
            name='forum_link',
        ),
        migrations.AddField(
            model_name='class',
            name='forum_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
