# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161004_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='amazon',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
