# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='amazon',
        ),
    ]
